# ==============================================================================
# CONFIGURACIÓN PRINCIPAL DE KITTY TERMINAL
# ==============================================================================

# Incluimos los módulos separados para tener un hiper-orden
include fonts.conf
include window.conf
include tabs.conf
include behavior.conf
include keybinds.conf

# Tema actual (Catppuccin Mocha y configuración compartida)
include teme.conf
