[config]
reload_apps = true
set_wallpaper = true

[templates.firefox-dark]
input_path = "~/Bully-ye/matugen/templates/firefox-dark.css"
output_path = "/home/manuelmv/.mozilla/firefox/gmi5y4ec.default-release/chrome/userChrome-dark.css"

[templates.firefox-light]
input_path = "~/Bully-ye/matugen/templates/firefox-light.css"
output_path = "/home/manuelmv/.mozilla/firefox/gmi5y4ec.default-release/chrome/userChrome-light.css"
