# ==============================================================================
# CONFIGURACIÓN COMPLETA DE HYPRLAND
# ==============================================================================

# Cargar configuraciones separadas

# Cargar configuraciones separadas
source = ~/Bully-ye/hypr/$(~/Bully-ye/hypr/scripts/detect_machine.sh).conf

source = ./conf/monitors.conf
source = ./conf/autostart.conf
source = ./conf/environment.conf
source = ./conf/input.conf
source = ./conf/general.conf
source = ./conf/animations.conf
source = ./conf/windowrules.conf
source = ./conf/keybinds.conf
