# ------------------------------------------------------------------------------
# 2. INICIO AUTOMÁTICO (Autostart)
# ------------------------------------------------------------------------------
exec-once = waybar & hyprpaper & swaync
exec-once = nm-applet --indicator
# Gestor de autenticación (Necesario para apps que piden contraseña de root)
exec-once = /usr/lib/polkit-kde-authentication-agent-1
