# ------------------------------------------------------------------------------
# 5. APARIENCIA GENERAL Y BORDES
# ------------------------------------------------------------------------------
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    
    # Colores de bordes (puedes personalizarlos con códigos HEX)
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle # Alternativa: master
}


# ------------------------------------------------------------------------------
# 6. DECORACIÓN (Desenfoque, Sombras y Esquinas redondeadas)
# ------------------------------------------------------------------------------


# ------------------------------------------------------------------------------
# 8. AJUSTES DE LAYOUT (Dwindle)
# ------------------------------------------------------------------------------
dwindle {
    force_split = 2 # 0 -> sigue el ratón, 1 -> siempre a la izquierda/arriba, 2 -> siempre a la derecha/abajo
    preserve_split = true 
}


# ------------------------------------------------------------------------------
# 9. MISCELÁNEOS
# ------------------------------------------------------------------------------

