# ------------------------------------------------------------------------------
# 5. APARIENCIA GENERAL Y BORDES
# ------------------------------------------------------------------------------
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    
    # Colores de bordes (puedes personalizarlos con códigos HEX)
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle # Alternativa: master
}


# ------------------------------------------------------------------------------
# 6. DECORACIÓN (Desenfoque, Sombras y Esquinas redondeadas)
# ------------------------------------------------------------------------------


# ------------------------------------------------------------------------------
# 8. AJUSTES DE LAYOUT (Dwindle)
# ------------------------------------------------------------------------------
dwindle {
    pseudotile = true # Mantiene proporciones de ventanas flotantes
    preserve_split = true # Evita que todo cambie al borrar ventanas
}


# ------------------------------------------------------------------------------
# 9. MISCELÁNEOS
# ------------------------------------------------------------------------------

