# -----------------------------------------------------
# Apps Config
# -----------------------------------------------------

bind = $mainMod, Return, exec, kitty
bind = $mainMod, R, exec, rofi -show drun
bind = $mainMod, W, exec, ~/Bully-ye/wallpaper-carousel/run-carousel.sh
bind = $mainMod, B, exec, firefox
bind = $mainMod, S, exec, spotify
bind = $mainMod, E, exec, dolphin
