# -----------------------------------------------------
# Apps Config
# -----------------------------------------------------

bind = $mainMod, Return, exec, kitty
bind = $mainMod, E, exec, thunar # Gestor de archivos
bind = $mainMod, R, exec, rofi -show drun
bind = $mainMod, W, exec, ~/Bully-ye/wallpaper-carousel/run-carousel.sh
bind = $mainMod, B, exec, firefox
