# -----------------------------------------------------
# Media & Screenshots Config
# -----------------------------------------------------

bind = $mainMod SHIFT, S, exec, FILE="$HOME/Imágenes/Capturas/$(date +'%Y-%m-%d_%H-%m-%S').png" && grim -g "$(slurp)" "$FILE" && wl-copy < "$FILE"
