# -----------------------------------------------------
# Media & Screenshots Config
# -----------------------------------------------------

# Volumen (teclas multimedia)
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind   = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Brillo (teclas multimedia - requiere 'brightnessctl')
bindel = , XF86MonBrightnessUp, exec, brightnessctl s 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl s 5%-

bind = $mainMod SHIFT, S, exec, FILE="$HOME/Imágenes/Capturas/$(date +'%Y-%m-%d_%H-%m-%S').png" && grim -g "$(slurp)" "$FILE" && wl-copy < "$FILE"
