# ~/.zshrc - ZSH Configuration Modularizada & Súper Vitaminada

ZSH_CONFIG_DIR="$HOME/Bully-ye/zsh"

# Cargar módulos en orden lógico
source "$ZSH_CONFIG_DIR/history.zsh"
source "$ZSH_CONFIG_DIR/completion.zsh"
source "$ZSH_CONFIG_DIR/keybindings.zsh"
source "$ZSH_CONFIG_DIR/aliases.zsh"
source "$ZSH_CONFIG_DIR/plugins.zsh"
source "$ZSH_CONFIG_DIR/prompt.zsh"