[ColorEffects:Disabled]
ChangeSelectionColor=true
Color=56,56,56
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
EnabledByDefault=true
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=112,111,110
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
EnabledByDefault=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate={{colors.dark.surface_container.rgb}}
BackgroundNormal={{colors.dark.surface_container_low.rgb}}
DecorationFocus={{colors.dark.primary.rgb}}
DecorationHover={{colors.dark.primary.rgb}}
ForegroundActive={{colors.dark.on_surface.rgb}}
ForegroundInactive={{colors.dark.on_surface_variant.rgb}}
ForegroundLink={{colors.dark.primary.rgb}}
ForegroundNegative={{colors.dark.error.rgb}}
ForegroundNeutral={{colors.dark.secondary.rgb}}
ForegroundNormal={{colors.dark.on_surface.rgb}}
ForegroundPositive={{colors.dark.tertiary.rgb}}
ForegroundVisited={{colors.dark.tertiary.rgb}}

[Colors:Selection]
BackgroundAlternate={{colors.dark.primary.rgb}}
BackgroundNormal={{colors.dark.primary.rgb}}
DecorationFocus={{colors.dark.primary.rgb}}
DecorationHover={{colors.dark.primary.rgb}}
ForegroundActive={{colors.dark.on_primary.rgb}}
ForegroundInactive={{colors.dark.on_primary.rgb}}
ForegroundLink={{colors.dark.on_primary.rgb}}
ForegroundNegative={{colors.dark.error.rgb}}
ForegroundNeutral={{colors.dark.on_primary.rgb}}
ForegroundNormal={{colors.dark.on_primary.rgb}}
ForegroundPositive={{colors.dark.on_primary.rgb}}
ForegroundVisited={{colors.dark.on_primary.rgb}}

[Colors:Tooltip]
BackgroundAlternate={{colors.dark.surface_container_high.rgb}}
BackgroundNormal={{colors.dark.surface_container_high.rgb}}
DecorationFocus={{colors.dark.primary.rgb}}
DecorationHover={{colors.dark.primary.rgb}}
ForegroundActive={{colors.dark.on_surface.rgb}}
ForegroundInactive={{colors.dark.on_surface_variant.rgb}}
ForegroundLink={{colors.dark.primary.rgb}}
ForegroundNegative={{colors.dark.error.rgb}}
ForegroundNeutral={{colors.dark.secondary.rgb}}
ForegroundNormal={{colors.dark.on_surface.rgb}}
ForegroundPositive={{colors.dark.tertiary.rgb}}
ForegroundVisited={{colors.dark.tertiary.rgb}}

[Colors:View]
BackgroundAlternate={{colors.dark.surface_container_lowest.rgb}}
BackgroundNormal={{colors.dark.surface.rgb}}
DecorationFocus={{colors.dark.primary.rgb}}
DecorationHover={{colors.dark.primary.rgb}}
ForegroundActive={{colors.dark.on_surface.rgb}}
ForegroundInactive={{colors.dark.on_surface_variant.rgb}}
ForegroundLink={{colors.dark.primary.rgb}}
ForegroundNegative={{colors.dark.error.rgb}}
ForegroundNeutral={{colors.dark.secondary.rgb}}
ForegroundNormal={{colors.dark.on_surface.rgb}}
ForegroundPositive={{colors.dark.tertiary.rgb}}
ForegroundVisited={{colors.dark.tertiary.rgb}}

[Colors:Window]
BackgroundAlternate={{colors.dark.surface_container_low.rgb}}
BackgroundNormal={{colors.dark.surface.rgb}}
DecorationFocus={{colors.dark.primary.rgb}}
DecorationHover={{colors.dark.primary.rgb}}
ForegroundActive={{colors.dark.on_surface.rgb}}
ForegroundInactive={{colors.dark.on_surface_variant.rgb}}
ForegroundLink={{colors.dark.primary.rgb}}
ForegroundNegative={{colors.dark.error.rgb}}
ForegroundNeutral={{colors.dark.secondary.rgb}}
ForegroundNormal={{colors.dark.on_surface.rgb}}
ForegroundPositive={{colors.dark.tertiary.rgb}}
ForegroundVisited={{colors.dark.tertiary.rgb}}

[General]
ColorScheme=MatugenDark
Name=Matugen Dark
shadeSortColumn=true

[KDE]
ColorScheme=MatugenDark
LookAndFeelPackage=org.kde.breezedark.desktop
contrast=4
widgetStyle=Breeze

[WM]
activeBackground={{colors.dark.surface.rgb}}
activeBlend={{colors.dark.surface.rgb}}
activeForeground={{colors.dark.on_surface.rgb}}
inactiveBackground={{colors.dark.surface_container.rgb}}
inactiveBlend={{colors.dark.surface_container.rgb}}
inactiveForeground={{colors.dark.on_surface_variant.rgb}}
activeBorder={{colors.dark.primary.rgb}}
inactiveBorder={{colors.dark.outline.rgb}}
